src/Entity/Articles.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticlesRepository")
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

	/**
	 *  @ORM\ManyToOne(targetEntity="App\Entity\User")
	 */
	private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $link;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $guid;

    /**
     * @ORM\Column(type="datetime")
     */
    private $pubdate;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $keywords = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $thumbnail_url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $source;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getGuid(): ?string
    {
        return $this->guid;
    }

    public function setGuid(?string $guid): self
    {
        $this->guid = $guid;

        return $this;
    }

    public function getPubdate(): ?\DateTimeInterface
    {
        return $this->pubdate;
    }

    public function setPubdate(\DateTimeInterface $pubdate): self
    {
        $this->pubdate = $pubdate;

        return $this;
    }

    public function getKeywords(): ?array
    {
        return $this->keywords;
    }

    public function setKeywords(?array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setCreator(?string $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(?\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    public function getThumbnailUrl(): ?string
    {
        return $this->thumbnail_url;
    }

    public function setThumbnailUrl(?string $thumbnail_url): self
    {
        $this->thumbnail_url = $thumbnail_url;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user')
            ->add('title')
            ->add('description')
            ->add('link')
            ->add('category')
            ->add('guid')
            ->add('pubdate')
            ->add('keywords')
            ->add('creator')
            ->add('modified')
            ->add('thumbnail_url')
            ->add('source')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/articles")
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/", name="articles_index", methods={"GET"})
     */
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesRepository->findAll()
        ]);
    }


    /**
     * @Route("/new", name="articles_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('articles_index');
        }

        return $this->render('articles/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="articles_show", methods={"GET"})
     */
    public function show(Articles $article): Response
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="articles_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Articles $article): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('articles_index', [
                'id' => $article->getId(),
            ]);
        }

        return $this->render('articles/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articles_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Articles $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articles_index');
    }



}

templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/articles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articles{% endblock %}

{% block content %}
    {% include 'nav.html.twig' %}
    <h1>Edit Articles</h1>

    {{ include('articles/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('articles_index') }}">back to list</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}

{% block content %}
    {% include 'nav.html.twig' %}
    <h1>Articles</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User</th>
                <th>Title</th>
                <th>Description</th>
                <th>Link</th>
                <th>Category</th>
                <th>Guid</th>
                <th>Pubdate</th>
                <th>Keywords</th>
                <th>Creator</th>
                <th>Modified</th>
                <th>Thumbnail_url</th>
                <th>Source</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.user }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.description }}</td>
                <td>{{ article.link }}</td>
                <td>{{ article.category }}</td>
                <td>{{ article.guid }}</td>
                <td>{{ article.pubdate ? article.pubdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.keywords ? article.keywords|join(', ') : '' }}</td>
                <td>{{ article.creator }}</td>
                <td>{{ article.modified ? article.modified|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.thumbnailUrl }}</td>
                <td>{{ article.source }}</td>
                <td>
                    <a class = "tab" href="{{ path('articles_show', {'id': article.id}) }}">Show</a>
                    <a class = "tab" href="{{ path('articles_edit', {'id': article.id}) }}">Edit</a>
                    {{ include('articles/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="tab" href="{{ path('homepage') }}">Home</a>
    <a class="tab" href="{{ path('articles_new') }}">Create new</a>
{% endblock %}

templates/articles/index.xml.twig
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
      xmlns:dc="http://purl.org/dc/elements/1.1/"
      xmlns:media="http://search.yahoo.com/mrss/">
    <channel>
        <title>{{ rss_feed_title }}</title>
        <link>{{ rss_feed_url}}</link>
        <description>{{ rss_feed_description }}</description>
        <language>{{ rss_feed_lang }}</language>
        <copyright>{{ rss_feed_copyright }}</copyright>
        {% for article in articles %}
            <item>
                {% if article.title is not defined and article.title is not null %}
                    <title/>
                {% else %}
                    <title>{{ article.title }}</title>
                {% endif %}

                {% if article.description is not defined and article.description is not null %}
                    <description/>
                {% else %}
                    <description>{{ article.description }}</description>
                {% endif %}

                {% if article.link is not defined and article.link is not null %}
                    <link/>
                {% else %}
                    <link>{{ article.link }}</link>
                {% endif %}

                <pubDate>{{ article.pubdate ? article.pubdate|date('r') : '' }}</pubDate>

                {% if article.guid is not defined and article.guid is not null %}
                    <guid/>
                {% else %}
                    <guid>{{ article.guid }}</guid>
                {% endif %}

                {% if article.source is not defined and article.source is not null %}
                    <source/>
                {% else %}
                    <source url="{{ article.source }}">{{ article.creator }}</source>
                {% endif %}

                {% if article.category is not defined and article.category is not null %}
                    <category/>
                {% else %}
                    <category>{{ article.category }}</category>
                {% endif %}

                {% if article.keywords is not defined and article.keywords is not null %}
                    <media:keywords/>
                {% else %}
                    {% set keywordString = "" %}
                    {% for keyword in article.keywords %}
                        {% if not loop.last %}
                            {% set keywordString = keywordString ~ keyword ~ "," %}
                        {% else %}
                            {% set keywordString = keywordString ~ keyword %}
                        {% endif %}
                    {% endfor %}
                    <media:keywords>{{ keywordString }}</media:keywords>
                {% endif %}


                {% if article.creator is not defined and article.creator is not null %}
                    <dc:creator/>
                {% else %}
                    <dc:creator>{{ article.creator }}</dc:creator>
                {% endif %}

                {% if article.modified is not defined and article.modified is not null %}
                    <dc:modified/>
                {% else %}
                    <dc:modified>{{ article.modified ? article.modified|date('Y-m-d H:i:s') : '' }}</dc:modified>
                {% endif %}


                {% if article.thumbnailUrl is defined %}
                    <media:thumbnail url="{{ article.thumbnailUrl }}"/>
                {% endif %}

            </item>
        {% else %}

        {% endfor %}
    </channel>
</rss>

templates/articles/index_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}


{% block content %}
    {% include 'nav.html.twig' %}
    <h1>URL to post</h1>

    <h3>Copy/paste this URL in Fedilab settings</h3>
    <code>{{ url }}</code> <button id="copy_content" class="btn btn-light">Copy</button>
    <br/><br/>

    <form method="post" action="{{ path('regenerate_token')}}" onsubmit="return confirm('Are you sure you want to regenerate a token?');">
        <input type="hidden" name="_method" value="POST">
        <input type="hidden" name="_token" value="{{ csrf_token('regenerate') }}">
        <button class="btn btn-danger">Regenerate a token</button>
    </form>

    <br/>
    <a href="{{ path('articles_index') }}" class="btn btn-link">See articles</a>
    <input type="hidden" value="{{ url }}" id="sharing_url"/>


{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        $('#copy_content').on('click', function(e) {
            var $temp = $("<input>");
            $("body").append($temp);
            $temp.val($("#sharing_url").val()).select();
            document.execCommand("copy");
            $temp.remove();
        });
    </script>
{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articles{% endblock %}

{% block content %}
    {% include 'nav.html.twig' %}
    <h1>Create new Articles</h1>

    {{ include('articles/_form.html.twig') }}

    <a class="tab" href="{{ path('articles_index') }}">Back to list</a>
{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block content %}
    {% include 'nav.html.twig' %}
    <h1>Articles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>User</th>
                <td>{{ article.user }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Link</th>
                <td><a href='{{ article.link }}' target="_blank">{{ article.link }}</a></td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ article.category }}</td>
            </tr>
            <tr>
                <th>Guid</th>
                <td><a href='{{ article.guid }}' target="_blank">{{ article.guid }}</a></td>
            </tr>
            <tr>
                <th>Pubdate</th>
                <td>{{ article.pubdate ? article.pubdate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Keywords</th>
                <td>{{ article.keywords ? article.keywords|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Creator</th>
                <td>{{ article.creator }}</td>
            </tr>
            <tr>
                <th>Modified</th>
                <td>{{ article.modified ? article.modified|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Thumbnail_url</th>
                <td><a href='{{ article.thumbnailUrl }}' target="_blank">{{ article.thumbnailUrl }}</a></td>
            </tr>
            <tr>
                <th>Source</th>
                <td><a href='{{ article.source }}' target="_blank">{{ article.source }}</a></td>
            </tr>
        </tbody>
    </table>

    <a class="tab" href="{{ path('articles_index') }}">Back to list</a>

    <a class="tab" href="{{ path('articles_edit', {'id': article.id}) }}">Edit</a>

    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}